spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/notepad_db
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      connection-timeout: 60000
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog.sql
server:
  error:
    include-message: always
    include-stacktrace: never
  port: 8082
