spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/notepad_db
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      connection-timeout: 60000
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  error:
    include-message: always
    include-stacktrace: never
  port: 8082
